#:schema node_modules/wrangler/config-schema.json
# Docs:
# - https://developers.cloudflare.com/workers/wrangler/configuration/
name = "a1d-photon"
main = "src/index.ts"
compatibility_date = "2024-07-01"
compatibility_flags = ["nodejs_compat"]

[vars]
WHITE_LIST = 'r2.cloudflarestorage.com,githubusercontent.com'